# Generated by Selenium IDE
import csv
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import sqlite3


class Test():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_(self):
        self.driver.get("http://mp.weixin.qq.com/")
        self.vars["window_handles"] = self.driver.window_handles
        # 等待.new-creation__menu-item:nth-child(2) svg出现
        WebDriverWait(self.driver, 60).until(expected_conditions.presence_of_element_located(
            (By.CSS_SELECTOR, ".new-creation__menu-item:nth-child(2) svg")))
        self.driver.find_element(
            By.CSS_SELECTOR, ".new-creation__menu-item:nth-child(2) svg").click()
        self.vars["win670"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win670"])
        self.driver.find_element(By.ID, "js_editor_insertlink").click()
        self.driver.find_element(
            By.XPATH, "//button[contains(.,\'选择其他公众号\')]").click()
        # 从mp.csv中读取公众号名称
        with open('mp.csv', 'r', encoding='utf-8') as f:
            reader = csv.reader(f)
            for row in reader:
                # 输入公众号名称
                self.driver.find_element(
                    By.CSS_SELECTOR, ".weui-desktop-search__wrp .weui-desktop-form__input").send_keys(row[0])
                self.driver.find_element(
                    By.CSS_SELECTOR, ".weui-desktop-search__wrp .weui-desktop-form__input").send_keys(Keys.ENTER)
                time.sleep(1)
                # 选择第一个公众号.inner_link_account_item的第一个
                self.driver.find_element(
                    By.CSS_SELECTOR, ".inner_link_account_item:nth-child(1)").click()
                # 循环class 为 .inner_link_article_item的 label 标签
                for i in range(1, 10):
                    # span = self.driver.find_element(By.CSS_SELECTOR, f".inner_link_article_item:nth-child({i}) > div span:nth-child(2)")
                    label = self.driver.find_element(
                        By.CSS_SELECTOR, f".inner_link_article_item:nth-child({i})")
                    title = label.find_element(
                        By.CSS_SELECTOR, "div span").text
                    publish_date = label.find_element(
                        By.CSS_SELECTOR, ".inner_link_article_date").text
                    link = label.find_element(
                        By.CSS_SELECTOR, "a").get_attribute("href")
                    # 写入sqlite3
                    conn = sqlite3.connect('mp.db')
                    c = conn.cursor()

                    c.execute(
                        "INSERT INTO mp (title, publish_date, link) VALUES (?, ?, ?)", (title, publish_date, link))
                    conn.commit()


if __name__ == '__main__':
    pytest.main(["-v", "-s", "test_mp.py"])
